### ISSUE TITLE
New API planning

### ISSUE THREAD

**Issue by s-ol** [unXedDani/Artal#6]
I think it would make sense to split the API in a few components, like so:

- 'raw' loader - loads PSD file into a rather flat table structure, loads images as `ImageData`.  
  this shouldn't do 'semantic parsing' - e.g. combining / renaming open-close/group layers etc. but stay true to the PSD format for the most part. It should also be safe to run in a thread (= no love.graphics access) and configurable to skip loading imagedatas, or load only the composed info.
- parser - takes the 'raw' output and reorganizes it into a tree that resembles the layer structure in a modern photoshop version - with group nodes and rasterized layers as leaves. Turns the `ImageData`s into `Image`s. The tree logic would resemble [this code](https://github.com/s-ol/gayngine/blob/master/psdscene.moon#L97-L112).
- renderer code - provides ways to render layers, layer groups and whole files correctly. I have a complete collection of photoshop blendmode shaders [here](https://github.com/s-ol/gayngine/tree/master/shaders), but not all of them have been tested. The renderer code would resemble [this code](https://github.com/s-ol/gayngine/blob/master/psdscene.moon#L237-L279).

**Comment by EvineDev** [comment]
Hey,
- Raw loader sounds good. `Artal.newPsd(file, "info")` + `Artal.newPsd(file, layerNumber)` kinda does this currently. But a single Api would be better.
- We only do a little bit of semantic parsing which is matching the closing layers with open layers and using the utf8 names of layers. I believe the closing layers is always named something like `</closing layer>`
- Parser sounds good, Maybe it's a good idea to have a more general "Utility" functions. Such as layername filtering etc.
- Renderer code. Good idea also pretty difficult one.
